
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 18 20:48:49 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 35;
  public static final int CONST = 8;
  public static final int LEVA_UGLASTA = 5;
  public static final int MINUS_MINUS = 29;
  public static final int NOT_EQUAL = 23;
  public static final int LPAREN = 11;
  public static final int GREATER = 24;
  public static final int SEMI = 4;
  public static final int MINUS = 18;
  public static final int RPAREN = 13;
  public static final int COMMA = 7;
  public static final int DIV = 20;
  public static final int QUESTION_MARK = 30;
  public static final int LESSER = 26;
  public static final int DESNA_UGLASTA = 6;
  public static final int PLUS = 15;
  public static final int ASSIGN = 9;
  public static final int EOF = 0;
  public static final int PLUS_PLUS = 28;
  public static final int EQUAL = 22;
  public static final int GREATER_EQUAL = 25;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int MUL = 19;
  public static final int NUMBER = 33;
  public static final int IDENT = 32;
  public static final int VOID = 12;
  public static final int DVE_TACKE = 31;
  public static final int LBRACE = 10;
  public static final int READ = 17;
  public static final int RBRACE = 3;
  public static final int PROG = 2;
  public static final int LESSER_EQUAL = 27;
  public static final int BOOL_CONST = 34;
  public static final int PERCENTAGE = 21;
  public static final int PRINT = 14;
}

